DazzleJewelry/DazzleJewelry/Controllers/AdminController.cs
using DazzleJewelry.Filter;
using DazzleJewelry.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace DazzleJewelry.Controllers
{
    [AdminFilter]
    public class AdminController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly IJewelryRepository _jewelryRepository;
        private readonly IOrderRepository _orderRepository;

        public AdminController(ICategoryRepository categoryRepository, IJewelryRepository jewelryRepository, IOrderRepository orderRepository)
        {
            _categoryRepository = categoryRepository;
            _jewelryRepository = jewelryRepository;
            _orderRepository = orderRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Jewelrys()
        {
            return View(_jewelryRepository.GetAllJewelry);
        }

        public IActionResult JewelryPage(int? id)
        {
            Jewelry jewelry = new Jewelry();
            if (id.HasValue)
            {
                jewelry = _jewelryRepository.GetJewelryById(id.Value);
            }
            ViewBag.categoryId = _categoryRepository.GetAllCategories
            .Select(c => new SelectListItem
            {
                Text = c.CategoryName,
                Value = c.CategoryId.ToString()
            }).ToList();
            return View(jewelry);
        }

        [HttpPost]
        public async Task<IActionResult> JewelrySave(Jewelry jewelry)
        {
            if (jewelry != null)
            {
                var file = Request.Form.Files.First();
                string savePath = Path.Combine("wwwroot", "images");
                var fileName = $"{DateTime.Now:MMddHHmmss}.{file.FileName.Split(".").Last()}";
                var fileUrl = Path.Combine(savePath, fileName);
                using (var fileStream = new FileStream(fileUrl, FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }
                jewelry.ImgUrl = "\\images\\" + fileName;
                jewelry.ImgThumUrl = "\\images\\thumbnails\\" + fileName;
                _jewelryRepository.SaveJewelry(jewelry);
            }
            return Redirect("Jewelrys");
        }
        public IActionResult Category()
        {
            return View(_categoryRepository.GetAllCategories);
        }

        public IActionResult Orders()
        {
            return View(_orderRepository.getAll());
        }

        public IActionResult DeleteOrder(int id)
        {
            _orderRepository.DeleteOrder(id);
            return RedirectToAction("Orders");
        }

        public IActionResult CreateCategory(Category category)
        {
            _categoryRepository.CreateCategory(category);
            return Redirect("Category");
        }
        public IActionResult DeleteCategory(int id)
        {
            _categoryRepository.DeleteCategory(id);
            return RedirectToAction("Category");
        }
    }
}

DazzleJewelry/DazzleJewelry/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DazzleJewelry.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

DazzleJewelry/DazzleJewelry/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/content/site.css" rel="stylesheet" />
    <title>Admin Panel</title>
</head>
<body>

    <div class="container">
        <div class="headerContent">
            <div class="home-header">
                <a href="/home/index">
                    <img class="img-responsive" src="~/images/logo.png" width="255" height="50" />
                </a>
            </div>
            <div class="navigation">
                <div>
                    <div id="divUcTopMenu">
                        <ul class="HeaderMenu2" id="HeaderMenu2">
                            <li class="ulVar">
                                <a asp-controller="Admin" asp-action="Index">Anasayfa</a>
                            </li>
                            <li class="ulVar">
                                <a asp-controller="Admin" asp-action="Category">Kategoriler</a>
                            </li>
                            <li class="ulVar">
                                <a asp-controller="Admin" asp-action="Jewelrys">Takılar</a>
                            </li>
                            <li class="ulVar">
                                <a asp-controller="Admin" asp-action="Orders">Siparişler</a>
                            </li>

                        </ul>
                    </div>
                </div>

            </div>

            <div class="col-md-12">
                @RenderBody()

            </div>
            @RenderSection("Scripts", required: false)
        </div>

    </div>





</body>
</html>

DazzleJewelry/DazzleJewelry/Views/Shared/_Carousel.cshtml
<div id="carousel" class="carousel slide">
    <ol class="carousel-indicators">
        <li data-target="#carousel" data-slide-to="0" class="active"></li>
        <li data-target="#carousel" data-slide-to="1"></li>
        <li data-target="#carousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="item active">
            <img src="~/images/kolyeler.jpg" style="width: 100%; height: 100%;" />

        </div>
        <div class="item">
            <img src="~/images/yuzukler.jpg" style="width: 100%; height: 100%;" />

        </div>
        <div class="item">
            <img src="~/images/tasarim-kupeler.jpg" style="width: 100%; height: 100%;" />

        </div>
    </div>
</div>

<script>
        $("carousel").carousel(
            {
                interval: 2000
            });
</script>

DazzleJewelry/DazzleJewelry/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/content/site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="container">
        <div class="headerContent">
            <div class="home-header">
                <a href="/home/index">
                    <img class="img-responsive" src="~/images/logo.png" width="255" height="50" />
                </a>
            </div>
            <div class="navigation">
                <div>
                    <div id="divUcTopMenu">
                        <ul class="HeaderMenu2" id="HeaderMenu2">
                            <li class="ulVar">
                                <a asp-controller="Home" asp-action="Index" target="_self">ANASAYFA</a>
                            </li>
                            @await Component.InvokeAsync("CategoryMenu")
                            <li class="ulVar">
                                <a asp-controller="Contact" asp-action="Index" target="_self">İLETİŞİM</a>
                            </li>
                            @await Component.InvokeAsync("ShoppingCartSummary")

                            <partial name="_LoginPartial" />

                        </ul>
                    </div>
                </div>

            </div>

            <div class="col-md-12">
                @RenderBody()

            </div>
            @RenderSection("Scripts", required: false)
        </div>

    </div>


</body>
</html>

DazzleJewelry/DazzleJewelry/Views/Shared/_jewelryCard.cshtml
@model Jewelry
<div class="col-lg-4 col-md-4 col-sm-4">

    <div class="thumbnail">

        <img src="@Model.ImgThumUrl" alt="image for jewelry shop" />

        <div class="caption">
            <h2><a asp-controller="Jewelry" asp-action="Details" asp-route-id="@Model.JewelryId">@Model.Name</a></h2>
            <div class="productItem">
                <div class="productDetail">
                    <div class="productName detailUrl">
                        <p>@Model.Description</p>
                    </div>
                </div>
                <div class="productPrice">
                    <div class="discountPrice">
                        <span><b>@Model.Price.ToString("c")</b></span>
                    </div>
                </div>
            </div>

        </div>


        <div class="mycartIcon tip" title="Sepete Ekle">
            <a class="btnAddToCart"
               asp-controller="ShoppingCart"
               asp-action="AddToShoppingCart"
               asp-route-jewelryId="@Model.JewelryId">

                <span class="urunListeSpanSepeteEkle">
                    Sepete Ekle
                </span>
            </a>

        </div>

    </div>
</div>